- .travis.yml
- README.md
- pom.xml
- src/main/java/org/zalando/stups/tokens/AbstractJsonFileBackedCredentialsProvider.java
- src/main/java/org/zalando/stups/tokens/AccessToken.java
- src/main/java/org/zalando/stups/tokens/AccessTokenConfiguration.java
- src/main/java/org/zalando/stups/tokens/AccessTokenEndpointException.java
- src/main/java/org/zalando/stups/tokens/AccessTokenRefresher.java
- src/main/java/org/zalando/stups/tokens/AccessTokenUnavailableException.java
- src/main/java/org/zalando/stups/tokens/AccessTokens.java
- src/main/java/org/zalando/stups/tokens/AccessTokensBuilder.java
- src/main/java/org/zalando/stups/tokens/ClientCredentials.java
- src/main/java/org/zalando/stups/tokens/ClientCredentialsProvider.java
- src/main/java/org/zalando/stups/tokens/CredentialsUnavailableException.java
- src/main/java/org/zalando/stups/tokens/JsonFileBackedClientCredentialsProvider.java
- src/main/java/org/zalando/stups/tokens/JsonFileBackedUserCredentialsProvider.java
- src/main/java/org/zalando/stups/tokens/Tokens.java
- src/main/java/org/zalando/stups/tokens/UserCredentials.java
- src/main/java/org/zalando/stups/tokens/UserCredentialsProvider.java
- src/test/java/org/zalando/stups/tokens/AccessTokenRefresherTest.java
java-source-files, add coveralls-config, add travis.yml for auto-build
> use stups-parent-pom for common maven, add license-header to all

- src/main/java/org/zalando/stups/tokens/AccessTokenRefresher.java
- src/test/java/org/zalando/stups/tokens/AccessTokenRefresherInitTest.java
Allow specifying "fixed" OAuth2 access tokens for local testing via environment variable OAUTH2_ACCESS_TOKENS:
export OAUTH2_ACCESS_TOKENS=mytok=abc123-456
> #4: read OAUTH2_ACCESS_TOKENS environment variable

- src/main/java/org/zalando/stups/tokens/AbstractHttpProvider.java
- src/test/java/org/zalando/stups/tokens/AbstractHttpProviderTest.java
> Fix index out of bounds exception.

- pom.xml
- src/main/java/org/zalando/stups/tokens/AbstractHttpProvider.java
- src/main/java/org/zalando/stups/tokens/AccessTokenConfiguration.java
- src/main/java/org/zalando/stups/tokens/AccessTokenEndpointException.java
- src/main/java/org/zalando/stups/tokens/AccessTokenRefresher.java
- src/main/java/org/zalando/stups/tokens/AccessTokenUnavailableException.java
- src/main/java/org/zalando/stups/tokens/AccessTokensBuilder.java
- src/main/java/org/zalando/stups/tokens/CredentialsUnavailableException.java
- src/main/java/org/zalando/stups/tokens/HttpConfig.java
- src/main/java/org/zalando/stups/tokens/Tokens.java
- src/main/java/org/zalando/stups/tokens/util/Objects.java
- src/test/java/org/zalando/stups/tokens/AccessTokenBuilderTest.java
- src/test/java/org/zalando/stups/tokens/AccessTokenConfigurationTest.java
- src/test/java/org/zalando/stups/tokens/AccessTokenRefresherRunTest.java
- src/test/java/org/zalando/stups/tokens/HttpConfigTest.java
- src/test/java/org/zalando/stups/tokens/util/ObjectsTest.java
- src/test/resources/log4j.dtd
- src/test/resources/log4j.xml
... will provide more test in the next days ;-)
> first set of tests

- src/main/java/org/zalando/stups/tokens/AccessTokenRefresher.java
- src/main/java/org/zalando/stups/tokens/AccessTokensBuilder.java
- src/main/java/org/zalando/stups/tokens/SimpleClientCredentials.java
- src/main/java/org/zalando/stups/tokens/TokenRefresherConfiguration.java
- src/test/java/org/zalando/stups/tokens/AccessTokenBuilderTest.java
- src/test/java/org/zalando/stups/tokens/AccessTokenRefresherRunTest.java
- src/test/java/org/zalando/stups/tokens/SimpleCredentialsTest.java
merge-conflicts resolved simple tests added
> Mostlymagic feature/make executorservice configurable

- src/main/java/org/zalando/stups/tokens/AccessTokenRefresher.java
- src/test/java/org/zalando/stups/tokens/AccessTokenRefresherRunTest.java
By merging #14, the possibility to inject a fixed OAuth2 token was broken. The change unconditionally instantiated the `HttpProvider` which tried to get the necessary credentials from the filesystem.
But as `CREDENTIALS_DIR` is not set for local testing, the application does not startup because of the `IllegalArgumentException` being thrown.
This PR fixes this by postponing the creation of the `HttpProvider` until the first access token has to be created.
> Do not try to refresh access token if fixed OAuth2 token is injected

- src/main/java/org/zalando/stups/tokens/AccessTokenRefresher.java
- src/test/java/org/zalando/stups/tokens/AccessTokenRefresherRunTest.java
Additionally to the problems fixed with #32, #14 moved the retrieval of `ClientCredentials` and `UserCredentials` to the `AccessTokenRefresher::start` method, which means that they are only read once and then never again.
As mint rotates the credentials, applications using the tokens library >= 0.93 will fail on the next rotation as the `*Credentials` instances are never updated.
Based on #32 this pull request restores the way of creating a new `HttpProvider` for every request as it was before.
> Fix refreshing of HTTP credentials

- src/main/java/org/zalando/stups/tokens/AccessTokens.java
- src/main/java/org/zalando/stups/tokens/Tokens.java
Not finalized yet - simply to get first feedback on documentation style. See #50 for further information / discussion.
@LappleApple / @jbellmann / @harti2006 can you have a look and let me know whether that style of documentation is fine for you?
@ePaul any feedback from your side whether this actually helps will also be welcome of course.
This PR should not yet be merged!
> Should add some first JavaDoc

- README.md
The readers have to guess otherwise
> Make it clear which classes are being used

- pom.xml
> use default-scope (compile) for httpclient-dependency

- pom.xml
- src/main/java/org/zalando/stups/tokens/AccessTokensBuilder.java
- src/main/java/org/zalando/stups/tokens/mcb/MCB.java
- src/main/java/org/zalando/stups/tokens/mcb/MCBConfig.java
- src/main/java/org/zalando/stups/tokens/util/Objects.java
fixes #71 
Experiences issues during javadoc generation.
> Fix problems during release

- pom.xml
> Release 0.10.0

- pom.xml
- src/main/java/org/zalando/stups/tokens/Tokens.java
- src/test/java/org/zalando/stups/tokens/AccessTokenBuilderTest.java
Add some tests to keep coverage.
> Should provide integration with OAUTH2_ACCESS_TOKEN_URL env variable

- src/main/java/org/zalando/stups/tokens/mcb/Closed.java
> To avoid concurrency-issues, just reset the counter

- src/main/java/org/zalando/stups/tokens/fs/AccessTokenDto.java
- src/main/java/org/zalando/stups/tokens/fs/AccessTokenHandler.java
- src/main/java/org/zalando/stups/tokens/fs/DefaultFileSystemTokenContentExtractor.java
- src/main/java/org/zalando/stups/tokens/fs/FilesystemSecretRefresher.java
- src/main/java/org/zalando/stups/tokens/fs/FilesystemSecretsRefresherConfiguration.java
- src/main/java/org/zalando/stups/tokens/fs/JwtFileSystemTokenContentExtractor.java
- src/main/java/org/zalando/stups/tokens/fs/SecretDto.java
- src/main/java/org/zalando/stups/tokens/fs/SecretsHandler.java
- src/main/java/org/zalando/stups/tokens/fs/TokenContentExtractor.java
- src/test/java/org/zalando/stups/tokens/fs/AccessTokenHandlerTest.java
- src/test/java/org/zalando/stups/tokens/fs/DefaultFileSystemTokenContentExtractorTest.java
- src/test/java/org/zalando/stups/tokens/fs/FilesystemSecretRefresherTest.java
- src/test/java/org/zalando/stups/tokens/fs/JwtFileSystemTokenContentExtractorTest.java
- src/test/java/org/zalando/stups/tokens/fs/SecretsHandlerTest.java
> Extract more info if possible from token

- MAINTAINERS
- pom.xml
> Added myself to maintainers list

- MAINTAINERS
- pom.xml
> Added myself to maintainers

- .zappr.yaml
- pom.xml
- src/main/java/org/zalando/stups/tokens/AbstractAccessTokenRefresher.java
- src/main/java/org/zalando/stups/tokens/AccessTokensBuilder.java
- src/main/java/org/zalando/stups/tokens/FileSupplier.java
- src/main/java/org/zalando/stups/tokens/fs/FilesystemSecretRefresher.java
- src/test/java/org/zalando/stups/tokens/AccessTokenBuilderTest.java
- dependency upgrades
- minor code-smells fixed
- check for filesystem-layout first
> Merge changes from upcoming_0.12.x branch

- .zappr.yaml
stups will be closed in the next months
> Change team name to automata

- pom.xml
> Changes from release.

- src/main/java/org/zalando/stups/tokens/AbstractAccessTokenRefresher.java
- src/test/java/org/zalando/stups/tokens/AbstractAccessTokenRefresherTest.java
> Provide better error-messages

- .zappr.yaml
- README.md
> Update README on how to use on K8s and migration hints

- src/main/java/org/zalando/stups/tokens/TokenVerifyRunner.java
> Decrease log level to info

- .travis.yml
- pom.xml
> Bumped jackson to 2.9.9 due to CVE-2019-12086

- README.md
bumped into the duplicated "the the" while reading the section
> removed duplicate word from readme

- pom.xml
> Update jackson-databind to 2.9.9.2

- pom.xml
Merge release 0.13.0 to `master` brach.
> Release 0.13.0

- .github/workflows/build-with-maven.yml
- pom.xml
* Add Java 11 support
* Fix `jacoco-maven-plugin` configuration
Fixes #243
> Add Java 11 support

- pom.xml
> Release 0.14.0

- pom.xml
> Add release plugin configuration
